### ISSUE TITLE
Where should the FoundationPress parent theme be stored?

### ISSUE THREAD

**Issue by ronenschmitz** [thetrickster/FoundationPress-child#18]
Hi Chris,

normally, with WordPress, parent themes are stored on the same level aside their child themes.
Looking at your Install Quickstart it says "mv FoundationPress your-theme-name" (mv for move), which results in the parent theme to be move inside the child theme directory? Why is that, and does this have to be that way?

Thank you for your help!

**Comment by ronenschmitz** [comment]
We'll anyways: After reading this, 
http://foundation.zurb.com/forum/posts/19765-foundationpress-child-theme
I am done creating a child theme of FoundationPress, and that'll probably save me a lot of time. 
Also, in this article, it says that this child theme is outdated. 
Thanks anyways.

**Comment by thetrickster** [comment]
That README is wrong.  I'm correcting it right now.  The README is a combination of the original README from the FoundationPress project.  It should indicate that after you clone this repo you should `mv FoundationPress-child my-theme-name`.  If you use the command currently in the README you will be moving the parent Foundation theme if its present and that's not good!

**Comment by ronenschmitz** [comment]
Thank you for that. I guess your answer will save some people some time. ;-)
Cheers.
